sudo: required
dist: trusty
language: node_js
addons:
apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - libkrb5-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run check
script: npm run test
node_js:
  - '10.2.x'
cache:
  directories:
  - node_modules
