sudo: false
dist: bionic
language: node_js
node_js:
  - 12.4.0
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libkrb5-dev
      - libsecret-1-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run check
script: npm run test
cache: npm
