image: Visual Studio 2017
platform: x64
os: unstable

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 10 x64
  - set CI=1	  
  - npm install -g npm@latest
  - npm ci

# TODO (@imlucas) Attach webdriver/electron logs to CI runs.
# https://www.appveyor.com/docs/packaging-artifacts/#pushing-artifacts-from-scripts

artifacts:
  # pushing all *.nupkg files in build directory recursively
  # - path: '**\*.nupkg'
  - path: '*.md'

build: off
test_script:
  - npm test